name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry & deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Lint with Black
        run: poetry run black --check .

      - name: Sort imports with isort
        run: poetry run isort --check-only .

      - name: Run tests
        run: poetry run pytest -q

      - name: Build Docker image
        run: docker build . --tag ghcr.io/${{ github.repository_owner }}/news-crawler:latest

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/news-crawler:latest
