name: Scheduled Crawl

# Runs every 15 minutes
# on:
#   schedule:
#     - cron: '*/15 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry & deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Run Async Fetcher
        env:
          RABBITMQ_URL: ${{ secrets.RABBITMQ_URL }}
          RAW_PAGES_QUEUE: raw_pages
        run: |
          poetry run python -m crawler.fetch_async \
            --max 100 \
            --concurrency 10 \
            --rate-interval 2.0
